
version: "3.9"
services:
  app:
    container_name: app
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    entrypoint: sh -c "npm install && npm run dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - node_challenge_network

  database:
    build: 
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node_challenge_network

  webserver:
    container_name: webserver
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - node_challenge_network
networks:
 node_challenge_network:
    driver: bridge
volumes:
  mysql:
    driver: local